util/docker-container: create docker container
open-education-hub/hardware-software-interface pull request #3
Opened 2024-03-12 21:46 UTC by ALEX11BR

adds a dockerfile for this course's docker container

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/open-education-hub/ccas-internal/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

2024-03-12 22:13 UTC, gabrielmocanu requested changes
I will add here some other things:
1. Please move this intro a directory called `hsi-runner` instead of `docker-container`.
2. Keep the same structure as [here].
3. You can copy the README file from there and change only URLs
4. Add a Makefile, similar to [here]

[here]: https://github.com/open-education-hub/operating-systems/tree/main/util/os-runner

2024-03-12 22:13 UTC, gabrielmocanu commented on util/docker-container/Dockerfile
> +CMD [ "bash" ]
```suggestion
RUN apt-get update \
    && apt-get install -y \
        gcc \
        gcc-multilib \
        nasm \
        make \
        build-essential \
        binutils \
        gdb \
        vim \
        nano \
        tmate \
        python2.7 \
        python3.10 \
        python-is-python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD [ "bash" ]
```

2024-03-12 22:13 UTC, gabrielmocanu commented on util/docker-container/Dockerfile
> +CMD [ "bash" ]
[Here] are some best practices about Dockerfile. We need to put all these commands inside a single one in order to have fewer layers.

[Here]: https://docs.docker.com/develop/develop-images/instructions/

2024-03-13 07:18 UTC, teodutu commented
Why are you adding this here? It will generate merge conflicts and not be available for the cs-pub-ro repo [1] until we sync them. I think it's best to do the development on our fork [1] and then periodically sync it [1] with this one via a PR bot such as [2].

[1] https://github.com/cs-pub-ro/hardware-software-interface/
[2] https://github.com/open-education-hub/operating-systems/pull/350

2024-03-30 16:36 UTC, gabrielmocanu commented
OK, @ALEX11BR , I think @teodutu  is right, sorry for confusion.
Please close this PR and open the same PR but on this repo: https://github.com/cs-pub-ro/hardware-software-interface/

2024-03-30 22:04 UTC, closed without merging